// flow-typed signature: bac5dd8f250931b78e0247556c2b4008
// flow-typed version: <<STUB>>/date-fns_v1.30.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'date-fns'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'date-fns' {
  declare module.exports: any;
}
