// flow-typed signature: 498a7927ed0f0dc10a1468625b3a634d
// flow-typed version: <<STUB>>/immutable_v4.0.0-rc.10/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'immutable' {
  declare module.exports: any;
}
