// flow-typed signature: 60d30a177f8e7a94ed70457fadd0abe0
// flow-typed version: <<STUB>>/lattice-auth_v0.7.0/flow_v0.79.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lattice-auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lattice-auth' {
  declare module.exports: any;
}
