// flow-typed signature: eaddbe9aaeabe33676e155f6a6d196d7
// flow-typed version: <<STUB>>/lattice_v0.37.0/flow_v0.79.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lattice'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lattice' {
  declare module.exports: any;
}
