// flow-typed signature: bdcb0a86fbd34b6338bdb3719f7cf5b3
// flow-typed version: <<STUB>>/lattice-sagas_v0.4.0/flow_v0.79.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lattice-sagas'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lattice-sagas' {
  declare module.exports: any;
}
