// flow-typed signature: f0653c2d36a95337df7c5a2b7bc23469
// flow-typed version: <<STUB>>/lattice-auth_v0.22.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lattice-auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lattice-auth' {
  declare module.exports: any;
}
