// flow-typed signature: 0e2a269b243da6df21986ddf01382b50
// flow-typed version: <<STUB>>/redux-immutable_v4.0.0/flow_v0.79.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-immutable' {
  declare module.exports: any;
}
