// flow-typed signature: 016e77562e5e1f8865b7ab922ce58251
// flow-typed version: <<STUB>>/styled-components_v5.2.1/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-components' {
  declare module.exports: any;
}
